// Flight School levels: the story of flight in order.
// Each level has lesson slides (t = title, d = diagram, p = text, tp = toddler line, ui = optional slider),
// "how to fly" notes, a quiz bank (a[0] is the right answer; h = hard, only in Challenge mode),
// two Flight Cards to collect and timeline events for the final exam.
'use strict';

const LEVELS = [
  {
    id: 'balloon', icon: '🎈', name: 'Hot Air Balloons', year: '1783', era: 'classic', badge: 'Balloon Boss', input: 'hold',
    slides: [
      { t: 'Hot air is lighter!', d: 'b-heat', ui: { label: '🔥 Burner' },
        p: 'When you heat air, its tiny bits zoom around faster and spread out. A balloon full of spread-out hot air is lighter than the cool air around it, so it floats up. Slide the burner and watch!',
        tp: 'Hot air is light, so the balloon floats up!' },
      { t: 'A sheep, a duck and a rooster', d: 'b-animals',
        p: 'In 1783 two French brothers, Joseph and Étienne Montgolfier, built a giant balloon. The very first passengers were a sheep, a duck and a rooster! They flew for 8 minutes and landed safely.',
        tp: 'A sheep, a duck and a rooster flew first!' },
      { t: 'People take to the sky', d: 'b-people',
        p: 'Two months later, on November 21, 1783, two men floated over Paris for about 25 minutes. They were the first people ever to fly!',
        tp: 'Then people flew over Paris!' },
      { t: 'How do you steer a balloon?', d: 'b-steer',
        p: 'You can\'t turn a balloon! But the wind blows different ways at different heights. Pilots go up or down to find a wind blowing where they want to go.',
        tp: 'Go up and down to catch the wind!' },
    ],
    how: {
      goal: 'Ride the winds to the landing field and land gently on the big X.',
      keys: 'Hold <b>Space</b> (or ↑) to fire the burner. Let go to cool down and sink.',
      touch: 'Hold your finger on the screen to fire the burner. Let go to cool down and sink.',
      tip: 'Each layer of wind blows a different way. Watch the flags! Go too far? Find a wind that blows back.',
      toddler: 'Hold to go up, let go to come down!',
    },
    quiz: [
      { q: 'Why does a hot air balloon go up?', a: ['The hot air inside is lighter than the cool air around it', 'The flame pushes down on the ground like a rocket does', 'The fabric is so thin and light that it floats by itself', 'Warm sunshine pulls the balloon up toward the sky'], why: 'Heated air spreads out, so a balloon full of it weighs less than the same space of cool air. The heavier cool air pushes it up.' },
      { q: 'Who were the very first balloon passengers?', a: ['A sheep, a duck and a rooster', 'A cat, a dog and a parrot', 'A horse, a goat and a hen', 'Two pilots and their cook'], why: 'In September 1783 the Montgolfier brothers sent up a sheep, a duck and a rooster to make sure flying was safe.' },
      { q: 'Who built the first hot air balloons?', a: ['The Montgolfier brothers', 'The Wright brothers', 'The Lumière brothers', 'The Grimm brothers'], why: 'Joseph and Étienne Montgolfier were paper makers in France. Their balloons were cloth lined with paper.' },
      { q: 'What happens to air when you heat it?', a: ['It spreads out and gets lighter', 'It shrinks and gets heavier', 'It turns into tiny raindrops', 'It stays exactly the same'], why: 'Heat makes the tiny bits of air move faster and spread apart, so hot air is less dense.' },
      { q: 'How does a balloon pilot come down?', a: ['Lets the air inside cool off', 'Flaps the basket up and down', 'Turns the burner up higher', 'Throws the ropes over the side'], why: 'Cooler air is heavier, so the balloon slowly sinks. More heat would make it rise.' },
      { q: 'When did people first fly in a hot air balloon?', a: ['1783', '1903', '1927', '1969'], why: 'On November 21, 1783, two men flew over Paris. That\'s 120 years before the first airplane!' },
      { q: 'How do balloon pilots steer?', h: true, a: ['They change height to find wind going the right way', 'They turn a rudder that hangs under the basket', 'They all lean to one side of the basket together', 'They point the burner flame where they want to go'], why: 'Winds at different heights often blow in different directions, so going up or down is how you "steer".' },
    ],
    cards: [
      { e: '🎈', n: 'Montgolfier Balloon', y: '1783', f: 'Made of cloth and paper, it carried the first people into the sky over Paris.' },
      { e: '🐑', n: 'Montauciel the Sheep', y: '1783', f: 'Its name means "Climb-to-the-sky". It flew with a duck and a rooster!' },
    ],
    timeline: [{ y: 1783, s: 'People fly for the first time, in a hot air balloon' }],
  },
  {
    id: 'wing', icon: '🪽', name: 'Wings & Gliders', year: '1800s', era: 'classic', badge: 'Wing Wizard', input: 'hold',
    slides: [
      { t: 'The four forces of flight', d: 'w-forces',
        p: 'Around 1799, George Cayley of England figured out that flying is a tug of war between four forces. LIFT pushes up. WEIGHT pulls down. THRUST pushes forward. DRAG holds back.',
        tp: 'Lift goes up, weight goes down!' },
      { t: 'Bernoulli\'s big idea', d: 'w-bernoulli',
        p: 'In 1738 Daniel Bernoulli found that fast-moving air has LOWER pressure. A wing is shaped and tilted so air rushes faster over the top. Lower pressure on top, higher underneath: the wing gets pushed up!',
        tp: 'Fast air over the wing lifts it up!' },
      { t: 'Tilt it… but not too much!', d: 'w-stall', ui: { label: '📐 Tilt the wing' },
        p: 'Tilt a wing up and it shoves more air down, so you get more lift. But tilt it too far and the air can\'t hug the top any more. The lift suddenly drops. That\'s called a STALL. Try the slider!',
        tp: 'Tilt the wing. Too much? It stalls!' },
      { t: 'The Glider King', d: 'w-lilienthal',
        p: 'In the 1890s Otto Lilienthal made about 2,000 glider flights from a hill he built. Gliders have no engine. They trade height for speed, and ride bubbles of warm rising air called thermals.',
        tp: 'Gliders fly with no engine!' },
    ],
    how: {
      goal: 'Glide as far as you can and land on the field. Ride the shimmering thermals to climb!',
      keys: 'Hold <b>Space</b> (or ↑) to lift the nose. Let go to dive and speed up.',
      touch: 'Hold your finger on the screen to lift the nose. Let go to dive and speed up.',
      tip: 'Watch the arrows: green is lift, red is weight, orange is drag. Nose up too long and you\'ll STALL.',
      toddler: 'Hold to go up, let go to zoom down!',
    },
    quiz: [
      { q: 'What are the four forces of flight?', a: ['Lift, weight, thrust and drag', 'Push, pull, spin and stop', 'Wind, rain, sun and snow', 'Up, down, fast and slow'], why: 'Lift and weight fight up and down. Thrust and drag fight forward and back.' },
      { q: 'Bernoulli found that fast-moving air has…', a: ['Lower pressure', 'Higher pressure', 'No pressure at all', 'The very same pressure'], why: 'Air rushing over the top of a wing has lower pressure than the air underneath, so the wing is pushed up.' },
      { q: 'A tilted wing pushes air down. What does the air do?', a: ['It pushes the wing up', 'It turns into a cloud', 'It makes the wing heavier', 'It pushes the wing backward'], why: 'Every push has a push back. Shove air down and it shoves the wing up.' },
      { q: 'What is a stall?', a: ['When a wing tilts too far and loses lift', 'When the engine gets too hot to keep going', 'When a plane parks at the airport gate', 'When the wheels drag along the runway'], why: 'Tilt a wing too far and the air can\'t flow smoothly over the top, so the lift suddenly drops.' },
      { q: 'Who made about 2,000 glider flights in the 1890s?', a: ['Otto Lilienthal', 'Amelia Earhart', 'Neil Armstrong', 'Isaac Newton'], why: 'Lilienthal\'s careful notes and photos helped inspire the Wright brothers.' },
      { q: 'What is a thermal?', a: ['A bubble of warm, rising air', 'A warm jacket for pilots', 'A tiny engine for gliders', 'A cold wind from the north'], why: 'Sun-warmed ground heats the air above it, which rises. Gliders and big birds circle in thermals to climb for free.' },
      { q: 'Which force pulls an airplane down?', a: ['Weight', 'Lift', 'Thrust', 'Drag'], why: 'Weight is gravity pulling down on the plane. Lift has to be at least as strong to stay up.' },
      { q: 'Who first worked out the four forces, around 1799?', h: true, a: ['George Cayley', 'Otto Lilienthal', 'Daniel Bernoulli', 'Orville Wright'], why: 'George Cayley is called the "father of aviation". He even built a glider that carried a person in 1853.' },
    ],
    cards: [
      { e: '📜', n: 'George Cayley', y: '1799', f: 'The "father of aviation" figured out lift, weight, thrust and drag.' },
      { e: '🦅', n: 'Otto Lilienthal', y: '1891', f: 'The Glider King made about 2,000 flights from a hill he built.' },
    ],
    timeline: [{ y: 1891, s: 'Otto Lilienthal starts flying his gliders' }],
  },
  {
    id: 'zeppelin', icon: '🎐', name: 'Zeppelins', year: '1900', era: 'ragtime', badge: 'Airship Captain', input: 'stick',
    slides: [
      { t: 'Giant flying ships', d: 'z-rigid',
        p: 'In 1900 Count Ferdinand von Zeppelin flew his first airship over a lake in Germany. Inside its long skin was a light metal skeleton holding big bags of gas. Engines pushed it along, and fins steered it.',
        tp: 'A zeppelin is a giant flying ship full of gas!' },
      { t: 'The problem with hydrogen', d: 'z-gas', ui: { label: '🧪 Hydrogen ↔ Helium' },
        p: 'Zeppelins were filled with hydrogen, the lightest gas there is. It lifts really well, but it catches fire very easily! Helium lifts almost as well and can never burn. Slide to compare.',
        tp: 'Hydrogen can catch fire. Helium is safe!' },
      { t: 'Going up and down', d: 'z-control',
        p: 'To go up, the crew dropped water ballast to make the ship lighter. To go down, they let some gas out. Sunshine warming the gas made it rise, and cool clouds made it sink!',
        tp: 'Drop water to go up, let gas out to go down!' },
      { t: 'The end of the airship age', d: 'z-hindenburg',
        p: 'In 1929 the Graf Zeppelin flew all the way around the world. But in 1937 the huge Hindenburg caught fire while landing in New Jersey. Most people on board escaped, but people stopped trusting hydrogen. Today\'s blimps use safe helium.',
        tp: 'Today\'s blimps use safe helium.' },
    ],
    how: {
      goal: 'Fly the zeppelin over the mountains and stop gently at the mooring mast. Stay away from lightning: hydrogen burns!',
      keys: 'Press <b>↑</b> to drop water ballast (go up). Press <b>↓</b> to let out gas (go down).',
      touch: 'Drag your thumb <b>up</b> to drop ballast (go up) and <b>down</b> to let out gas (go down).',
      tip: 'Airships are slow to react, so plan ahead! You only have so much ballast and gas.',
      toddler: 'Drag up to go up, drag down to go down!',
    },
    quiz: [
      { q: 'What gas filled the early zeppelins?', a: ['Hydrogen', 'Helium', 'Oxygen', 'Steam'], why: 'Hydrogen is the lightest gas there is, so it gives the most lift.' },
      { q: 'What is the big problem with hydrogen?', a: ['It catches fire very easily', 'It is far too heavy to fly', 'It smells like rotten eggs', 'It freezes into solid ice'], why: 'One spark can set hydrogen burning. That\'s why it is so dangerous in an airship.' },
      { q: 'What gas do blimps use today?', a: ['Helium, which can\'t burn', 'Hydrogen, which is cheaper', 'Oxygen, which we breathe', 'Steam, from boiling water'], why: 'Helium lifts almost as well as hydrogen and can never catch fire.' },
      { q: 'How does an airship crew make the ship go up?', a: ['Drop some water ballast', 'Let some of the gas out', 'Point the nose at the ground', 'Turn all the engines off'], why: 'Dropping heavy water makes the airship lighter, so the gas lifts it higher.' },
      { q: 'Who flew the first zeppelin, in 1900?', a: ['Count Ferdinand von Zeppelin', 'Captain Charles Lindbergh', 'Joseph-Michel Montgolfier', 'Engineer Igor Sikorsky'], why: 'The airships were named after him: zeppelins!' },
      { q: 'What happened to the Hindenburg in 1937?', a: ['It caught fire while landing', 'It flew all the way to the Moon', 'It became the first jet airliner', 'It got stuck on a mountain top'], why: 'The hydrogen caught fire. After that, big passenger airships stopped flying.' },
      { q: 'What amazing trip did the Graf Zeppelin make in 1929?', h: true, a: ['It flew all the way around the world', 'It carried the first astronaut to space', 'It broke the sound barrier over the sea', 'It landed on top of a tall skyscraper'], why: 'It circled the world in about 21 days, with passengers eating fancy meals on board!' },
    ],
    cards: [
      { e: '@zeppelin', n: 'Graf Zeppelin', y: '1929', f: 'Flew around the world in about 21 days, with passengers in comfy cabins.' },
      { e: '🔥', n: 'Hindenburg', y: '1937', f: 'The giant hydrogen airship caught fire while landing. After that, airships used helium.' },
    ],
    timeline: [{ y: 1900, s: 'The first zeppelin airship flies' }, { y: 1937, s: 'The Hindenburg fire ends the age of big airships' }],
  },
  {
    id: 'wright', icon: '🛩️', name: 'The Wright Brothers', year: '1903', era: 'ragtime', badge: 'Kitty Hawk Hero', input: 'stick',
    slides: [
      { t: 'Two brothers with a bike shop', d: 'r-shop',
        p: 'Wilbur and Orville Wright fixed bicycles in Dayton, Ohio. They built their own wind tunnel, a box with a fan, and tested more than 200 little wing shapes to find the best one.',
        tp: 'Two brothers fixed bikes and dreamed of flying!' },
      { t: 'The secret: control!', d: 'r-control',
        p: 'The Wrights figured out how to STEER: tip the nose up and down (pitch), roll the wings by twisting them (roll) and turn left and right (yaw). Their Flyer was twitchy on purpose, so the pilot had to keep correcting it.',
        tp: 'They learned how to steer a plane!' },
      { t: 'December 17, 1903', d: 'r-first',
        p: 'At Kitty Hawk, North Carolina, Orville flew the Wright Flyer for 12 seconds and 120 feet. It was the first flight of an airplane with an engine! That day they took turns, and Wilbur\'s best flight went 852 feet in 59 seconds.',
        tp: 'The first airplane flew for 12 seconds!' },
    ],
    how: {
      goal: 'Fly the Wright Flyer as far as you can. Beat Orville\'s 120 feet, then try for Wilbur\'s 852 feet! You get 3 flights.',
      keys: 'Use <b>↑</b> and <b>↓</b> to tip the nose up and down. Keep it steady!',
      touch: 'Drag your thumb up and down to tip the nose. Keep it steady!',
      tip: 'The Flyer wobbles on its own. Make small, gentle corrections, and don\'t climb too steeply or you\'ll slow down.',
      toddler: 'Drag up and down to keep the plane flying!',
    },
    quiz: [
      { q: 'Where did the first airplane flight happen?', a: ['Kitty Hawk, North Carolina', 'Dayton, Ohio, at home', 'Paris, in France', 'Lakehurst, New Jersey'], why: 'The Wrights lived in Dayton but flew at Kitty Hawk, which had strong steady winds and soft sand.' },
      { q: 'How long was the very first airplane flight?', a: ['12 seconds', '12 minutes', '12 hours', '2 seconds'], why: 'Orville\'s first flight lasted 12 seconds and went 120 feet, about the length of a blue whale.' },
      { q: 'What business did the Wright brothers run?', a: ['A bicycle shop', 'A bakery', 'A toy store', 'A shoe store'], why: 'Fixing bikes taught them about balance, chains and light, strong parts.' },
      { q: 'What did they build to test over 200 wing shapes?', a: ['A wind tunnel', 'A rocket', 'A submarine', 'A hot air balloon'], why: 'Their wind tunnel was a wooden box with a fan. It showed them which wing shapes lifted best.' },
      { q: 'What was the Wright brothers\' big secret?', a: ['Steering in the air: pitch, roll and yaw', 'A giant engine that was super strong', 'Wings painted gold so they would shine', 'Big wheels so the plane could take off'], why: 'Being able to steer and balance in the air is what made their airplane really work. (The Flyer didn\'t even have wheels!)' },
      { q: 'In what year did the first airplane fly?', a: ['1903', '1783', '1927', '1969'], why: 'December 17, 1903. Just 66 years later, people walked on the Moon!' },
      { q: 'How did the Wright Flyer roll its wings?', h: true, a: ['By twisting the wing tips', 'By moving a sail on top', 'By leaning a heavy weight', 'By spinning one propeller faster'], why: 'It\'s called wing warping. Twisting the wings made one side lift more than the other.' },
      { q: 'How far did Wilbur\'s best flight go on December 17, 1903?', h: true, a: ['852 feet', '12 feet', '120 miles', '3 miles'], why: 'Wilbur flew 852 feet in 59 seconds, the longest flight of that first day.' },
    ],
    cards: [
      { e: '@wright', n: 'Wright Flyer', y: '1903', f: 'A 12-horsepower engine, two propellers, and no wheels: it took off from a wooden rail.' },
      { e: '🚲', n: 'Wilbur & Orville', y: '1903', f: 'Two bicycle builders from Dayton, Ohio, who figured out how to steer a plane.' },
    ],
    timeline: [{ y: 1903, s: 'The Wright brothers fly the first airplane' }],
  },
  {
    id: 'prop', icon: '✈️', name: 'Propeller Planes', year: '1920s', era: 'ragtime', badge: 'Atlantic Ace', input: 'stickbtn', button: { ico: '💦', lbl: 'WAKE UP' },
    slides: [
      { t: 'A propeller is a spinning wing', d: 'p-prop',
        p: 'Each propeller blade is shaped like a little wing. When the engine spins it, the blades push air backward and the plane gets pulled forward. That push is called THRUST.',
        tp: 'The propeller spins and pulls the plane!' },
      { t: 'Brave pilots', d: 'p-pilots',
        p: 'In 1921 Bessie Coleman became the first African American woman to earn a pilot\'s license. In 1932 Amelia Earhart became the first woman to fly alone across the Atlantic Ocean.',
        tp: 'Brave pilots flew all over the world!' },
      { t: 'Across the ocean!', d: 'p-atlantic',
        p: 'In 1927 Charles Lindbergh flew alone from New York to Paris in 33 and a half hours. His plane had no front window (a fuel tank was in the way!), so he steered with a compass and fought to stay awake the whole way.',
        tp: 'Lindbergh flew all the way across the ocean!' },
    ],
    how: {
      goal: 'Fly Lindbergh\'s route from New York to Paris! Pass over each checkpoint, dodge storms and don\'t fall asleep.',
      keys: 'Steer with <b>←</b> and <b>→</b>. When your eyes get droopy, press <b>Space</b> to wake up!',
      touch: 'Drag left and right to steer. When your eyes get droopy, tap <b>WAKE UP</b>!',
      tip: 'The wind pushes you sideways, so aim a little into it. The dotted line shows the way to the next checkpoint.',
      toddler: 'Drag to steer to the next flag!',
    },
    quiz: [
      { q: 'A propeller is like a…', a: ['Spinning wing that pulls the plane forward', 'Fan that keeps the pilot nice and cool', 'Wheel that turns to drive on the runway', 'Brake that slows the plane for landing'], why: 'Propeller blades are shaped like wings. Spinning, they push air back, which pulls the plane forward.' },
      { q: 'Who flew alone, nonstop, from New York to Paris in 1927?', a: ['Charles Lindbergh', 'Orville Wright', 'Yuri Gagarin', 'Chuck Yeager'], why: 'Lindbergh flew the Spirit of St. Louis across the Atlantic and became world famous.' },
      { q: 'About how long did Lindbergh\'s flight take?', a: ['33 and a half hours', 'About 10 minutes', 'About 3 whole weeks', 'About 3 and a half hours'], why: 'He had to stay awake for the whole flight, more than a day and a night!' },
      { q: 'Who was the first woman to fly alone across the Atlantic?', a: ['Amelia Earhart', 'Bessie Coleman', 'Valentina Tereshkova', 'Sally Ride'], why: 'Amelia Earhart did it in 1932, flying from Canada to Northern Ireland.' },
      { q: 'Bessie Coleman was the first African American woman to…', a: ['Earn a pilot\'s license', 'Walk on the Moon\'s surface', 'Build a working jet engine', 'Fly a rescue helicopter'], why: 'No flight school in America would teach her, so she learned French and trained in France. She got her license in 1921.' },
      { q: 'What force does a propeller make?', a: ['Thrust', 'Weight', 'Drag', 'Gravity'], why: 'Thrust is the forward push. The propeller makes it by throwing air backward.' },
      { q: 'Why did Lindbergh need a periscope or side windows to see?', h: true, a: ['A big fuel tank blocked his front window', 'He was flying the plane upside down', 'It helped him see the stars at night', 'His seat faced backward in the plane'], why: 'Extra fuel mattered more than a front window, so the tank went right in front of him!' },
    ],
    cards: [
      { e: '@prop', n: 'Spirit of St. Louis', y: '1927', f: 'No front window! A fuel tank sat in front, so Lindbergh peeked out the sides.' },
      { e: '🎓', n: 'Bessie Coleman', y: '1921', f: 'Trained in France to become the first African American woman pilot.' },
    ],
    timeline: [{ y: 1927, s: 'Lindbergh flies alone across the Atlantic' }, { y: 1932, s: 'Amelia Earhart flies solo across the Atlantic' }],
  },
  {
    id: 'heli', icon: '🚁', name: 'Helicopters', year: '1939', era: 'adventure', badge: 'Rescue Pilot', input: 'stick',
    slides: [
      { t: 'Leonardo\'s dream', d: 'h-davinci',
        p: 'More than 500 years ago, the artist and inventor Leonardo da Vinci drew an "aerial screw", a machine that would spin and twist its way up into the air. It could never have flown, but the idea was amazing!',
        tp: 'Leonardo da Vinci dreamed of a spinning flying machine!' },
      { t: 'Spinning wings', d: 'h-rotor', ui: { label: '🌀 Rotor speed' },
        p: 'A helicopter\'s rotor blades are long, skinny wings that spin around. Spin them fast enough and they make more lift than the helicopter weighs, so it rises straight up! Try the slider.',
        tp: 'The spinning blades lift it straight up!' },
      { t: 'Tilt to move', d: 'h-tilt',
        p: 'To fly forward, the pilot tilts the spinning rotor forward, so some of its push points forward. Tilt it back to slow down. And a helicopter can HOVER, staying still in the air, which no airplane can do!',
        tp: 'Tilt the blades to fly forward!' },
      { t: 'The little tail rotor', d: 'h-tail',
        p: 'Spinning the big rotor one way tries to spin the helicopter the other way! In 1939 Igor Sikorsky solved it with a little rotor on the tail that pushes sideways. Most helicopters still use his design.',
        tp: 'The little tail rotor stops it spinning around!' },
    ],
    how: {
      goal: 'Rescue the hikers! Hover low over each one until they\'re winched up, then fly them back to the hospital helipad.',
      keys: '<b>↑</b> / <b>↓</b> to climb and sink. <b>←</b> / <b>→</b> to tilt and fly sideways.',
      touch: 'Drag your thumb: up and down to climb and sink, left and right to tilt and fly.',
      tip: 'Helicopters keep sliding after you tilt, so tilt the other way to stop. Keep the rotor away from the cliffs!',
      toddler: 'Drag to fly to the hikers and bring them home!',
    },
    quiz: [
      { q: 'What lifts a helicopter into the air?', a: ['Spinning rotor blades shaped like wings', 'A big balloon hidden inside the top', 'Jets of hot air blowing at the ground', 'Magnets that push away from the Earth'], why: 'Each rotor blade is a skinny wing. Spinning fast, they make lots of lift.' },
      { q: 'How does a helicopter fly forward?', a: ['It tilts its spinning rotor forward', 'It flaps its rotor blades like wings', 'It turns its tail rotor off and on', 'It points its skids toward the back'], why: 'Tilting the rotor makes part of its push point forward.' },
      { q: 'What does the little tail rotor do?', a: ['Stops the helicopter from spinning around', 'Pushes the helicopter high into the sky', 'Keeps the pilot cool on hot sunny days', 'Helps the helicopter float on water'], why: 'The big rotor tries to spin the body the other way. The tail rotor pushes sideways to stop it.' },
      { q: 'Who flew the first practical helicopter, in 1939?', a: ['Igor Sikorsky', 'Charles Lindbergh', 'Otto Lilienthal', 'Chuck Yeager'], why: 'Igor Sikorsky\'s VS-300 had one big rotor and a small tail rotor, like most helicopters today.' },
      { q: 'Who drew an "aerial screw" flying machine over 500 years ago?', a: ['Leonardo da Vinci', 'Isaac Newton', 'Daniel Bernoulli', 'George Cayley'], why: 'Leonardo da Vinci sketched it in the late 1400s. It couldn\'t fly, but it was a great idea!' },
      { q: 'Why are helicopters great for rescues?', a: ['They can hover and land almost anywhere', 'They are faster than any jet plane', 'They can fly all the way into space', 'They never need any fuel at all'], why: 'Hovering lets a helicopter lift people off mountains, boats and rooftops.' },
      { q: 'What does a helicopter\'s collective control do?', h: true, a: ['Makes all the blades bite more air to climb', 'Collects rescued people with a long rope', 'Steers the tail left and right', 'Switches the radio between channels'], why: 'The collective changes the angle of all the blades together: more angle, more lift.' },
    ],
    cards: [
      { e: '@heli', n: 'Sikorsky VS-300', y: '1939', f: 'One big rotor on top and a little one on the tail: the design most helicopters still use.' },
      { e: '🎨', n: 'Leonardo\'s Aerial Screw', y: '~1490', f: 'Leonardo da Vinci sketched a spinning screw that might twist up into the air.' },
    ],
    timeline: [{ y: 1939, s: 'Igor Sikorsky flies his helicopter' }],
  },
  {
    id: 'jet', icon: '🛫', name: 'Jets & Supersonic', year: '1947', era: 'jet', badge: 'Sound Barrier Breaker', input: 'stickbtn', button: { ico: '🔥', lbl: 'BURNER' },
    slides: [
      { t: 'Suck, squeeze, bang, blow!', d: 'j-engine',
        p: 'A jet engine SUCKS in air with a big fan, SQUEEZES it tight, adds fuel and BANGS it into fire, then BLOWS the hot gas out the back super fast. The first jet plane flew in 1939.',
        tp: 'Suck, squeeze, bang, blow!' },
      { t: 'Newton\'s third law', d: 'j-newton',
        p: 'Isaac Newton said every push has an equal push back the other way. Let go of a blown-up balloon: air shoots out one way, the balloon zooms the other. A jet blasts gas backward, so it zooms forward!',
        tp: 'Push air back, zoom forward!' },
      { t: 'Faster than sound', d: 'j-mach', ui: { label: '💨 Speed' },
        p: 'Sound travels about 1,235 km/h. That\'s Mach 1. On October 14, 1947, Chuck Yeager flew faster than sound for the first time. Slide past Mach 1 and watch the sound waves pile up into a SONIC BOOM!',
        tp: 'Faster than sound makes a BOOM!' },
      { t: 'Jumbo jets and Concorde', d: 'j-concorde',
        p: 'The 1969 Boeing 747 "Jumbo Jet" carried hundreds of people. Concorde (1976 to 2003) flew at Mach 2: London to New York in about 3 and a half hours! Its booms were so loud it only flew that fast over the ocean.',
        tp: 'Concorde flew twice as fast as sound!' },
    ],
    how: {
      goal: 'Fly Concorde: climb high, go supersonic once you\'re over the ocean, and reach Mach 2!',
      keys: '<b>↑</b> / <b>↓</b> to climb and dive. Hold <b>Space</b> for the afterburners.',
      touch: 'Drag up and down to climb and dive. Hold <b>BURNER</b> for the afterburners.',
      tip: 'Thin air high up means less drag. Afterburners gulp fuel! And no booms over towns: wait for the ocean.',
      toddler: 'Hold BURNER to go super fast!',
    },
    quiz: [
      { q: 'What are the four steps of a jet engine?', a: ['Suck, squeeze, bang, blow', 'Run, jump, hop, skip', 'Spin, stop, go, slow', 'Push, pull, lift, drop'], why: 'Suck air in, squeeze it, burn it with fuel (bang), and blow the hot gas out the back.' },
      { q: 'Newton\'s third law says…', a: ['Every push has an equal push back the other way', 'What goes up must always come down slowly', 'Heavy things always fall faster than light ones', 'Spinning things spin faster the longer they go'], why: 'A jet pushes gas backward, and the gas pushes the jet forward.' },
      { q: 'What is Mach 1?', a: ['The speed of sound', 'The speed of light', 'The speed of a cheetah', 'The top speed of a car'], why: 'Mach 1 is about 1,235 km/h near the ground. Mach 2 is twice as fast.' },
      { q: 'Who first flew faster than sound, in 1947?', a: ['Chuck Yeager', 'Charles Lindbergh', 'Wilbur Wright', 'Neil Armstrong'], why: 'Chuck Yeager flew the Bell X-1 past Mach 1 on October 14, 1947.' },
      { q: 'What is a sonic boom?', a: ['A loud bang when something goes faster than sound', 'The roar of thunder during a summer storm', 'The sound a jet engine makes as it starts up', 'The pop of a balloon when it bursts'], why: 'Sound waves pile up in front of a plane until they make a shock wave you hear as a BOOM.' },
      { q: 'Why did Concorde only fly supersonic over the ocean?', a: ['Its sonic booms were too loud over towns', 'The ocean air is warmer and smoother', 'It had to watch for ships to rescue', 'Its engines only worked near water'], why: 'Booms could rattle windows and scare people, so supersonic flight over land wasn\'t allowed.' },
      { q: 'How fast did Concorde cruise?', h: true, a: ['Mach 2, twice the speed of sound', 'Mach 1, just the speed of sound', 'Mach 10, ten times the speed of sound', 'Mach 0.5, half the speed of sound'], why: 'About 2,180 km/h! Passengers could see the curve of the Earth from its windows.' },
    ],
    cards: [
      { e: '🟠', n: 'Bell X-1', y: '1947', f: 'Chuck Yeager\'s rocket plane, Glamorous Glennis, was the first to beat Mach 1.' },
      { e: '@jet', n: 'Concorde', y: '1976', f: 'A supersonic airliner: London to New York in about 3½ hours at Mach 2.' },
    ],
    timeline: [{ y: 1947, s: 'Chuck Yeager flies faster than sound' }, { y: 1976, s: 'Concorde starts flying passengers at Mach 2' }],
  },
  {
    id: 'rocket', icon: '🚀', name: 'Rockets', year: '1926', era: 'space', badge: 'Rocket Scientist', input: 'stickbtn', button: { ico: '🔥', lbl: 'STAGE' },
    slides: [
      { t: 'Fire arrows', d: 'k-arrows',
        p: 'The very first rockets were invented in China about 800 years ago. They were arrows with tubes of gunpowder tied on. When the powder burned, hot gas blasted out the back and the arrow shot forward.',
        tp: 'The first rockets were fire arrows from China!' },
      { t: 'Rockets bring their own air', d: 'k-oxygen',
        p: 'Fire needs oxygen. Jets grab it from the air, but there is no air in space! So rockets carry their own oxygen in a tank, next to their fuel. That\'s why rockets can fly in space.',
        tp: 'Rockets carry their own air!' },
      { t: 'The first liquid-fuel rocket', d: 'k-goddard',
        p: 'On March 16, 1926, Robert Goddard launched the first rocket that burned liquid fuel. It flew for just 2 and a half seconds and went 41 feet high. Every big space rocket since then grew from his idea!',
        tp: 'Robert Goddard launched a little rocket!' },
      { t: 'Stages', d: 'k-stages',
        p: 'Big rockets come in stages, stacked like blocks. When one runs out of fuel, it drops off so the rest is lighter. The Saturn V Moon rocket had three stages and stood 111 meters tall. Since 2015, some boosters even fly back and land themselves!',
        tp: 'Empty parts drop off to make the rocket lighter!' },
      { t: 'Going sideways to stay up', d: 'k-turn',
        p: 'To get into orbit you don\'t just go up. You have to go SIDEWAYS super fast, about 28,000 km/h! So a rocket goes straight up, then slowly tips over as it climbs. That\'s called a gravity turn.',
        tp: 'Go up, then tip over and go sideways fast!' },
    ],
    how: {
      goal: 'Fly into orbit! Go up, then slowly tip over to follow the green guide arrow. Reach 7.8 km/s sideways speed.',
      keys: 'Tip the rocket with <b>←</b> <b>→</b>. When a stage runs out of fuel, press <b>Space</b> to STAGE.',
      touch: 'Drag left and right to tip the rocket. When a stage runs out of fuel, tap <b>STAGE</b>.',
      tip: 'Tip over too early and you\'ll crash back into the thick air. Too late and you\'ll just go up and fall back down.',
      toddler: 'Tap STAGE when the fuel runs out!',
    },
    quiz: [
      { q: 'Why can rockets fly in space but jets can\'t?', a: ['Rockets carry their own oxygen', 'Rockets are painted shiny white', 'Jets are far too heavy to lift off', 'Space is full of free rocket fuel'], why: 'Fire needs oxygen. Jets take it from the air, and there\'s no air in space, so rockets bring their own.' },
      { q: 'Why do big rockets have stages?', a: ['Dropping empty stages makes it lighter', 'Each stage is a room for astronauts', 'Stages make the rocket look taller', 'Stages help it float in the ocean'], why: 'Carrying empty tanks is a waste. Dropping them lets the rest of the rocket go faster.' },
      { q: 'Who launched the first liquid-fuel rocket in 1926?', a: ['Robert Goddard', 'Chuck Yeager', 'Amelia Earhart', 'Igor Sikorsky'], why: 'Robert Goddard\'s little rocket flew for 2.5 seconds in a field in Massachusetts.' },
      { q: 'Where were the first rockets invented?', a: ['China', 'America', 'Australia', 'Brazil'], why: 'Chinese inventors made gunpowder fire arrows about 800 years ago.' },
      { q: 'About how high up does space begin?', a: ['About 100 km', 'About 1 km', 'At the top of the clouds', 'About 10,000 km'], why: 'Most people say space begins about 100 km (62 miles) up, where the air is almost gone.' },
      { q: 'To get into orbit, a rocket needs to go…', a: ['Sideways super fast, not just straight up', 'Straight up as high as it possibly can', 'Slowly, so that it doesn\'t get too hot', 'Backward, so gravity can pull it along'], why: 'Orbit means moving sideways so fast (about 28,000 km/h) that you keep falling around the Earth.' },
      { q: 'What was special about a Falcon 9 booster in December 2015?', h: true, a: ['It flew back and landed itself', 'It carried the first dog to space', 'It was the first rocket ever built', 'It went all the way to Jupiter'], why: 'Landing boosters lets them fly again and again, which makes going to space much cheaper.' },
    ],
    cards: [
      { e: '🧪', n: 'Robert Goddard', y: '1926', f: 'His little liquid-fuel rocket flew 2.5 seconds. Every big rocket grew from it.' },
      { e: '@rocket', n: 'Saturn V', y: '1967', f: 'The giant Moon rocket: 111 meters tall, taller than the Statue of Liberty!' },
    ],
    timeline: [{ y: 1926, s: 'Robert Goddard launches a liquid-fuel rocket' }, { y: 2015, s: 'A rocket booster lands itself for the first time' }],
  },
  {
    id: 'space', icon: '🌙', name: 'To the Moon', year: '1969', era: 'space', badge: 'Moonwalker', input: 'stickbtn', button: { ico: '🔥', lbl: 'THRUST' },
    slides: [
      { t: 'What is an orbit?', d: 's-orbit',
        p: 'Throw a ball and it falls. Throw it faster and it lands farther away. Throw it SUPER fast, about 28,000 km/h, and the Earth curves away as fast as it falls. It falls around and around forever. That\'s an orbit!',
        tp: 'Super fast things fall around the Earth!' },
      { t: 'Firsts in space', d: 's-firsts',
        p: 'In 1957 Sputnik 1 became the first satellite. In 1961 Yuri Gagarin became the first person in space. In 1963 Valentina Tereshkova became the first woman in space.',
        tp: 'The first satellite, man and woman in space!' },
      { t: 'One giant leap', d: 's-moon',
        p: 'On July 20, 1969, Apollo 11 landed on the Moon. The computer was steering toward a field of boulders, so Neil Armstrong flew the Eagle himself and landed with less than a minute of fuel left! Then he and Buzz Aldrin walked on the Moon.',
        tp: 'People landed on the Moon!' },
      { t: 'Living in space', d: 's-iss',
        p: 'From 1981 to 2011 the Space Shuttle carried astronauts up and glided back down to a runway. It helped build the International Space Station, where people have lived since 2000. It goes around Earth every 90 minutes!',
        tp: 'Astronauts live in a space station!' },
    ],
    how: {
      goal: 'Land the Eagle gently on a flat landing spot. Stay away from the boulders, and watch your fuel!',
      keys: 'Hold <b>↑</b> or <b>Space</b> to fire the engine. Use <b>←</b> <b>→</b> to slide sideways.',
      touch: 'Drag your thumb: up fires the engine, left and right slide. Or hold <b>THRUST</b>.',
      tip: 'The speed numbers turn green when it\'s safe to land. You get 3 tries.',
      toddler: 'Hold THRUST to slow down and land softly!',
    },
    quiz: [
      { q: 'What does it mean to be in orbit?', a: ['Falling around Earth while zooming sideways', 'Floating because there is no gravity up there', 'Hanging from a very long, strong rope', 'Being pushed along by the solar wind'], why: 'Gravity still pulls on astronauts in orbit. They\'re falling, but moving sideways so fast they keep missing the Earth!' },
      { q: 'What was the first satellite, in 1957?', a: ['Sputnik 1', 'Apollo 11', 'The Hubble Telescope', 'Voyager 1'], why: 'Sputnik 1 was a shiny metal ball with antennas. It went "beep beep" as it orbited.' },
      { q: 'Who was the first person in space?', a: ['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'John Glenn'], why: 'Yuri Gagarin orbited the Earth once on April 12, 1961.' },
      { q: 'Who was the first woman in space?', a: ['Valentina Tereshkova', 'Amelia Earhart', 'Sally Ride', 'Bessie Coleman'], why: 'Valentina Tereshkova flew in 1963 and orbited Earth 48 times. (Sally Ride was the first American woman, in 1983.)' },
      { q: 'Who was the first person to walk on the Moon?', a: ['Neil Armstrong', 'Yuri Gagarin', 'Charles Lindbergh', 'Michael Collins'], why: 'On July 20, 1969, Neil Armstrong stepped onto the Moon, followed by Buzz Aldrin. Michael Collins circled above.' },
      { q: 'How strong is gravity on the Moon?', a: ['About one sixth of Earth\'s', 'Twice as strong as Earth\'s', 'Exactly the same as Earth\'s', 'Ten times stronger than Earth\'s'], why: 'If you can jump 1 foot high on Earth, you could jump about 6 feet on the Moon!' },
      { q: 'What is the International Space Station?', a: ['A home in orbit where astronauts live and work', 'A rocket engine that burns liquid hydrogen', 'An airport built on the side of the Moon', 'A telescope that looks at faraway stars'], why: 'People have lived on the ISS since the year 2000. It goes around the Earth about every 90 minutes.' },
      { q: 'How did the Space Shuttle come home?', h: true, a: ['It glided down and landed on a runway', 'It splashed down under big parachutes', 'It flew back using jet engines', 'It hovered down on rocket flames'], why: 'The Shuttle was the world\'s heaviest glider. It had no engines for landing, so it got one try!' },
    ],
    cards: [
      { e: '@space', n: 'Apollo 11 Eagle', y: '1969', f: 'The lunar module that landed Neil Armstrong and Buzz Aldrin on the Moon.' },
      { e: '👩‍🚀', n: 'Valentina Tereshkova', y: '1963', f: 'The first woman in space orbited Earth 48 times.' },
    ],
    timeline: [{ y: 1957, s: 'Sputnik 1 becomes the first satellite' }, { y: 1961, s: 'Yuri Gagarin becomes the first person in space' }, { y: 1969, s: 'Apollo 11 lands on the Moon' }, { y: 1981, s: 'The first Space Shuttle launches' }],
  },
  {
    id: 'drone', icon: '📦', name: 'Drones', year: '2010s', era: 'modern', badge: 'Drone Ace', input: 'stick',
    slides: [
      { t: 'What is a drone?', d: 'd-what',
        p: 'A drone is an aircraft with no pilot on board. It\'s flown by remote control, or by its own computer. Early ones were radio-controlled target planes in the 1930s, like the "Queen Bee". That may be where the name "drone" comes from!',
        tp: 'A drone flies with no pilot inside!' },
      { t: 'Four propellers', d: 'd-quad', ui: { label: '↔️ Fly sideways' },
        p: 'A quadcopter has four propellers. Two spin one way and two spin the other, so the drone doesn\'t spin around. To move, it spins some propellers faster than others, which tilts it. Try the slider!',
        tp: 'Four propellers spin to lift the drone!' },
      { t: 'A tiny flying brain', d: 'd-brain',
        p: 'Drones are packed with sensors: gyroscopes feel tilting, GPS knows where it is, and cameras see. A little computer uses them to make hundreds of tiny adjustments every second to keep the drone steady.',
        tp: 'A tiny computer keeps the drone steady!' },
      { t: 'Drones at work', d: 'd-jobs',
        p: 'Drones deliver medicine to faraway hospitals, help farmers check crops, film movies and find lost hikers. But there are rules: drones must stay far away from airports and keep away from crowds.',
        tp: 'Drones deliver things and help people!' },
    ],
    how: {
      goal: 'Deliver the packages! Hover over the warehouse to pick one up, then hover over the glowing house pad to drop it off.',
      keys: 'Fly with the <b>arrow keys</b>.',
      touch: 'Drag your thumb in any direction to fly.',
      tip: 'Keep an eye on your battery, and recharge at the warehouse. Stay out of the red no-fly zone around the airport!',
      toddler: 'Drag to fly the package to the house!',
    },
    quiz: [
      { q: 'What is a drone?', a: ['An aircraft with no pilot on board', 'A plane that only flies at night', 'A helicopter that needs two pilots', 'A balloon tied to the ground'], why: 'Drones are flown by remote control or by their own computer.' },
      { q: 'How many propellers does a quadcopter have?', a: ['Four', 'Two', 'Six', 'One'], why: '"Quad" means four. Some drones have six or eight, but quadcopters have four.' },
      { q: 'How does a quadcopter move sideways?', a: ['It spins some propellers faster to tilt', 'It flaps its arms like a bird does', 'It pushes off the air with its legs', 'It turns on a little jet in the back'], why: 'Tilting points some of the propellers\' push sideways, just like a helicopter.' },
      { q: 'Why do two propellers spin one way and two the other?', a: ['So the drone doesn\'t spin around', 'So the drone makes a nicer sound', 'So the propellers don\'t get tangled', 'So the battery lasts twice as long'], why: 'The two directions cancel each other out, like a helicopter\'s tail rotor.' },
      { q: 'Which is a rule for flying drones?', a: ['Stay far away from airports', 'Only fly above the clouds', 'Always fly as fast as you can', 'Only fly when it is raining'], why: 'A drone near an airport could get in the way of big planes, which is very dangerous.' },
      { q: 'Which is a real job drones do today?', a: ['Delivering medicine to faraway places', 'Carrying passengers to the Moon', 'Driving school buses through cities', 'Digging tunnels under mountains'], why: 'In Rwanda and other countries, drones drop blood and medicine to hospitals by parachute.' },
      { q: 'What keeps a drone steady in the air?', h: true, a: ['A computer using gyroscope sensors', 'A heavy weight hanging underneath', 'A tiny pilot riding on the top', 'A long tail like a kite has'], why: 'Gyroscopes feel the tiniest tilt, and the computer fixes it hundreds of times a second.' },
    ],
    cards: [
      { e: '@drone', n: 'Quadcopter', y: '2010s', f: 'Four propellers and a tiny computer that makes hundreds of adjustments every second.' },
      { e: '💉', n: 'Medicine Drones', y: '2016', f: 'In Rwanda, drones started dropping blood and medicine to hospitals by parachute.' },
    ],
    timeline: [{ y: 2016, s: 'Drones start delivering medicine in Rwanda' }],
  },
  {
    id: 'planet', icon: '🪐', name: 'Planet Travel', year: '1977', era: 'space', badge: 'Space Navigator', input: 'stickbtn', button: { ico: '🚀', lbl: 'LAUNCH' },
    slides: [
      { t: 'A curvy road to Mars', d: 'i-transfer', ui: { label: '📅 Launch day' },
        p: 'Spacecraft don\'t fly straight to Mars. Everything is circling the Sun, so a spacecraft coasts on a big curved path around the Sun. You have to launch at just the right time so Mars is there when you arrive. Slide to pick a launch day!',
        tp: 'Space ships fly a big curvy path to Mars!' },
      { t: 'Launch windows', d: 'i-window',
        p: 'Earth and Mars line up just right only about every 26 months. That\'s the launch window! The trip takes about 7 months. Miss the window and you wait over two years for the next one.',
        tp: 'You have to launch at just the right time!' },
      { t: 'Slingshots and Voyager', d: 'i-voyager',
        p: 'In 1977 the Voyager probes launched. They swung past giant planets to get speed boosts, called gravity assists. Voyager 1 is now farther away than anything people ever made, and it\'s still sending messages home!',
        tp: 'Voyager swung past planets to go faster!' },
      { t: 'Seven minutes of terror', d: 'i-terror',
        p: 'Radio signals take many minutes to reach Mars, so a lander must land all by itself! In 2021 Perseverance slowed down with a heat shield, then a huge parachute, then a rocket "sky crane" gently lowered it onto Mars on ropes.',
        tp: 'A sky crane lowered the rover onto Mars!' },
    ],
    how: {
      goal: 'Launch to Mars at the right moment, steer to meet the planet, then land your rover safely!',
      keys: 'Press <b>Space</b> to launch (hold <b>→</b> to fast-forward time). In flight, <b>←</b> <b>→</b> nudge your speed. Then <b>Space</b> for the parachute and to fire the sky crane.',
      touch: 'Tap <b>LAUNCH</b> when the path meets Mars (drag right to fast-forward). Then tap for the parachute and hold to fire the sky crane.',
      tip: 'The dotted line shows where you\'ll go. Launch when it meets the ghost of Mars!',
      toddler: 'Tap the button when the line touches Mars!',
    },
    quiz: [
      { q: 'How does a spacecraft travel to Mars?', a: ['On a big curved path around the Sun', 'In a straight line, like a laser beam', 'By riding along on a passing comet', 'By hopping from one star to the next'], why: 'Everything orbits the Sun, so the spacecraft coasts on a curved path that meets Mars.' },
      { q: 'How often do launch windows to Mars open?', a: ['About every 26 months', 'Every single day', 'Once every 100 years', 'Every Monday morning'], why: 'Earth and Mars only line up right about every 26 months.' },
      { q: 'About how long does a trip to Mars take?', a: ['About 7 months', 'About 7 hours', 'About 7 years', 'About 7 days'], why: 'Perseverance launched in July 2020 and landed in February 2021.' },
      { q: 'What is a gravity assist?', a: ['Swinging past a planet to speed up', 'Using magnets to pull a ship along', 'Parking on a moon to get more fuel', 'Pushing off an asteroid with legs'], why: 'A planet\'s gravity can fling a spacecraft faster, like a slingshot.' },
      { q: 'Which spacecraft has gone farther than anything else people made?', a: ['Voyager 1', 'Sputnik 1', 'Apollo 11', 'The Space Station'], why: 'Voyager 1 left our solar system\'s bubble in 2012 and is still going!' },
      { q: 'What are the "seven minutes of terror"?', a: ['A rover landing on Mars all by itself', 'Waiting for a rocket to launch', 'Floating outside the Space Station', 'Flying a helicopter on the Moon'], why: 'The landing takes about seven minutes, and the lander has to do it alone.' },
      { q: 'Why can\'t people drive a Mars rover with a joystick in real time?', h: true, a: ['Radio signals take minutes to get there', 'Mars is too cold for joysticks to work', 'The rover is too small to see on camera', 'Mars rovers don\'t have any batteries'], why: 'Depending on where the planets are, a signal takes about 3 to 22 minutes to reach Mars.' },
    ],
    cards: [
      { e: '🛰️', n: 'Voyager 1', y: '1977', f: 'After visiting Jupiter and Saturn, it left our solar system. It\'s still sending messages!' },
      { e: '@planet', n: 'Perseverance', y: '2021', f: 'A car-sized rover lowered onto Mars by a rocket-powered sky crane.' },
    ],
    timeline: [{ y: 1977, s: 'Voyager 1 and 2 launch to the outer planets' }, { y: 1976, s: 'Viking 1 lands on Mars' }],
  },
  {
    id: 'mars', icon: '🚁', name: 'Drones on Mars', year: '2021', era: 'mars', badge: 'Mars Flyer', input: 'stickbtn', button: { ico: '🌀', lbl: 'SPIN UP' },
    slides: [
      { t: 'Flying in super-thin air', d: 'm-thin', ui: { label: '🌍 Earth ↔ Mars 🔴' },
        p: 'Mars air is about 100 times thinner than Earth\'s, so wings and rotors have very little to push on. Gravity there is only about a third of Earth\'s, which helps. Slide to Mars and see how fast the rotor has to spin!',
        tp: 'Mars air is super thin, so the blades spin super fast!' },
      { t: 'Ingenuity', d: 'm-ingenuity',
        p: 'On April 19, 2021, a little helicopter called Ingenuity made the first powered flight on another planet! It weighs only 1.8 kg and its rotors spin about 2,400 times a minute. It carried a tiny piece of the Wright Flyer\'s wing.',
        tp: 'Ingenuity flew on Mars, with a piece of the Wright Flyer!' },
      { t: 'Flying by itself', d: 'm-auto',
        p: 'Messages take many minutes to reach Mars, so nobody could fly Ingenuity with a joystick. It flew itself, using its own camera and computer. It scouted ahead to find safe paths for the Perseverance rover.',
        tp: 'It flew all by itself and helped the rover!' },
      { t: 'A record breaker', d: 'm-record',
        p: 'Ingenuity was meant to fly 5 times. It flew 72 times over almost three years! A solar panel charged its battery every day. Next, NASA plans to send Dragonfly, a drone-copter, to Saturn\'s moon Titan.',
        tp: 'It flew 72 times!' },
    ],
    how: {
      goal: 'Spin up the rotors, then fly Ingenuity to photograph the 3 targets for the rover. Land on a smooth, rock-free spot before your battery runs out.',
      keys: 'Press <b>Space</b> to spin up. Then <b>↑</b> / <b>↓</b> to climb and sink, <b>←</b> <b>→</b> to tilt.',
      touch: 'Tap <b>SPIN UP</b>, then drag your thumb to fly.',
      tip: 'Hover inside a camera circle to snap a photo. Dust devils push you around!',
      toddler: 'Tap SPIN UP, then drag to fly to the circles!',
    },
    quiz: [
      { q: 'Why must Ingenuity\'s rotors spin super fast?', a: ['Mars air is super thin', 'Mars is very windy', 'Its blades are short', 'To keep warm at night'], why: 'Thin air gives the blades very little to push on, so they have to spin really fast.' },
      { q: 'About how fast did Ingenuity\'s rotors spin?', a: ['About 2,400 times a minute', 'About 24 times a minute', 'About 2 times a minute', 'About 240,000 times a minute'], why: 'That\'s about 40 spins every second!' },
      { q: 'What powered Ingenuity?', a: ['A solar panel that charged its battery', 'A tiny gas engine that burned fuel', 'A long cable plugged into the rover', 'The wind turning its blades for free'], why: 'Each Martian day, sunlight recharged its batteries for the next flight.' },
      { q: 'What special souvenir did Ingenuity carry?', a: ['A tiny piece of the Wright Flyer\'s wing', 'A signed photo of Charles Lindbergh', 'A little model of the Hindenburg', 'A propeller from an old zeppelin'], why: 'A stamp-sized piece of fabric from the 1903 Wright Flyer flew on Mars!' },
      { q: 'Why did Ingenuity fly itself?', a: ['Radio messages take minutes to reach Mars', 'Mars has no air for radio waves', 'NASA lost the remote control', 'The rover steered it with a joystick'], why: 'By the time a "turn left!" message arrived, it would be far too late.' },
      { q: 'When did Ingenuity first fly on Mars?', a: ['2021', '1969', '1903', '2001'], why: 'April 19, 2021: the first powered, controlled flight on another planet.' },
      { q: 'How many times did Ingenuity fly?', h: true, a: ['72 times', 'Just once', '7 times', '700 times'], why: 'It was planned for 5 flights and kept going for almost three years!' },
    ],
    cards: [
      { e: '@mars', n: 'Ingenuity', y: '2021', f: 'The first aircraft to fly on another planet. It carried a scrap of the Wright Flyer!' },
      { e: '🪐', n: 'Dragonfly', y: '2030s', f: 'A planned drone-copter to explore Titan, Saturn\'s moon with a thick, hazy sky.' },
    ],
    timeline: [{ y: 2021, s: 'Ingenuity flies on Mars' }],
  },
  {
    id: 'light', icon: '⚡', name: 'Light & Time Travel', year: '1905', era: 'cosmic', badge: 'Time Bender', input: 'stickbtn', button: { ico: '⚡', lbl: 'BOOST' },
    slides: [
      { t: 'The fastest thing there is', d: 'l-speed',
        p: 'Light zooms about 300,000 km every second. It could circle the Earth 7 and a half times in one second! Light from the Moon takes just over 1 second to reach us, and sunlight takes about 8 minutes.',
        tp: 'Light is the fastest thing ever!' },
      { t: 'Light-years', d: 'l-year',
        p: 'Space is so big that we measure it with light. A light-year is how far light goes in a whole year: about 9.5 trillion km. The nearest star after the Sun is over 4 light-years away. When you look at stars, you see light that left them long ago!',
        tp: 'Stars are so far away, their light takes years to get here!' },
      { t: 'The cosmic speed limit', d: 'l-limit', ui: { label: '🚀 Speed (% of light)' },
        p: 'In 1905 Albert Einstein showed that nothing can go faster than light. The closer a spaceship gets to light speed, the more energy each push takes. Reaching it would need endless energy! And something stranger happens: the ship\'s clock ticks slower. Try the slider!',
        tp: 'Nothing can go faster than light!' },
      { t: 'Time travel to the future?', d: 'l-twins',
        p: 'Zoom near light speed for a while and come home: less time has passed for you than on Earth. You\'ve jumped into the future! This is real. Even GPS satellites must fix their clocks for it. Astronauts on the Space Station age a tiny bit slower too.',
        tp: 'Going super fast is like jumping to the future!' },
      { t: 'And the past?', d: 'l-past',
        p: 'Going back in time is much harder to believe. If you went back and stopped your grandparents from meeting, you wouldn\'t be born to go back! Ideas like wormholes and warp drives are fun, but nobody knows how to make them, and most scientists doubt it\'s possible.',
        tp: 'Going back in time is a big puzzle!' },
    ],
    how: {
      goal: 'Fly to the star Proxima Centauri, 4.2 light-years away, and back! Get as close to light speed as you can. Watch your clock and Earth\'s clock.',
      keys: '<b>↑</b> / <b>↓</b> to dodge space dust. Press <b>Space</b> to BOOST with an energy cell.',
      touch: 'Drag up and down to dodge space dust. Tap <b>BOOST</b> to use an energy cell.',
      tip: 'Each boost gets you closer to light speed, but never all the way. Grab ⚡ cells to boost more!',
      toddler: 'Tap BOOST to go fast!',
    },
    quiz: [
      { q: 'How fast does light travel?', a: ['About 300,000 km every second', 'About 300 km every hour', 'About as fast as a jet plane', 'About as fast as sound'], why: 'Light is the fastest thing in the universe: 299,792 km per second.' },
      { q: 'How long does sunlight take to reach Earth?', a: ['About 8 minutes', 'No time at all', 'About 8 days', 'About 8 years'], why: 'The Sun is about 150 million km away, so its light takes about 8 minutes and 20 seconds.' },
      { q: 'What is a light-year?', a: ['How far light travels in a year', 'How long a year feels in space', 'A year with extra sunny days', 'How much a light beam weighs'], why: 'A light-year is a distance: about 9.5 trillion kilometers!' },
      { q: 'Can a spaceship reach the speed of light?', a: ['No, it would need endless energy', 'Yes, with a big enough engine', 'Yes, but only in empty space', 'No, because space is too cold'], why: 'The closer you get, the more energy each bit of speed takes. Light speed is the cosmic speed limit.' },
      { q: 'Who showed that fast-moving clocks tick slower?', a: ['Albert Einstein', 'Isaac Newton', 'Chuck Yeager', 'Robert Goddard'], why: 'Einstein\'s theory of relativity, from 1905, says time stretches when you go very fast.' },
      { q: 'You zoom near light speed, then come home. What happened?', a: ['Less time passed for you than on Earth', 'More time passed for you than on Earth', 'The same time passed for everyone', 'Time went backward for everyone'], why: 'Your clock ticked slower, so you come home to the future!' },
      { q: 'Why do GPS satellites need their clocks corrected?', h: true, a: ['Speed and gravity change how fast their clocks tick', 'Their old batteries make the clocks run too slow', 'Space is far too dark and cold for clocks to work', 'They are set to a different time zone than ours'], why: 'Without Einstein\'s corrections, GPS maps would drift by kilometers every day!' },
      { q: 'Why do most scientists doubt travel to the past?', h: true, a: ['It makes puzzles where effects come before causes', 'Time machines would be too heavy to lift off', 'The past is much too far away to see', 'Clocks are only made to go forward'], why: 'Like the grandparent puzzle: if you changed the past, you might never exist to change it.' },
    ],
    cards: [
      { e: '🧠', n: 'Albert Einstein', y: '1905', f: 'Showed that nothing can beat light, and that fast-moving clocks tick slower.' },
      { e: '@light', n: 'A Beam of Light', y: '299,792 km/s', f: 'Light could zoom around the Earth about 7½ times in one second!' },
    ],
    timeline: [{ y: 1905, s: 'Einstein explains light speed and stretchy time' }],
  },
  {
    id: 'aliens', icon: '👽', name: 'Are We Alone?', year: 'Today', era: 'cosmic', badge: 'Cosmic Detective', input: 'stick',
    slides: [
      { t: 'So many planets!', d: 'a-planets',
        p: 'In 1995 astronomers found the first planet circling a star like our Sun. Now we know more than 5,000 of these "exoplanets"! Many stars have planets, and some are just the right distance for liquid water. So is anybody out there?',
        tp: 'There are planets around lots of stars!' },
      { t: 'Where is everybody?', d: 'a-fermi',
        p: 'Our galaxy has hundreds of billions of stars. In 1950 the scientist Enrico Fermi asked: if life is common, where is everybody? Maybe space is just too huge. Our radio signals have only traveled about 100 light-years, and the galaxy is 100,000 across!',
        tp: 'Space is so big, it\'s hard to find anyone!' },
      { t: 'Thinking like a detective', d: 'a-evidence',
        p: 'Scientists haven\'t found strong evidence of aliens yet. Blurry UFO videos usually turn out to be balloons, planes, birds or camera glare. Carl Sagan said: amazing claims need amazing evidence. Check the simple explanation first!',
        tp: 'Check the simple answer first!' },
      { t: 'Still searching', d: 'a-search',
        p: 'We\'ve only searched a tiny bit of space, like scooping one glass of water from the ocean and saying "no fish!" Scientists listen with radio telescopes, study planets\' air with telescopes, and look for tiny life on Mars and in the oceans under the ice of Jupiter\'s moon Europa.',
        tp: 'Scientists keep looking and listening!' },
    ],
    how: {
      goal: 'Be a radio astronomer! Scan the sky to find 5 signals, then use your detective skills to decide what each one really is.',
      keys: 'Move the telescope with the <b>arrow keys</b>. Follow the signal meter: it beeps faster when you\'re close!',
      touch: 'Drag your thumb to move the telescope. Follow the signal meter: it beeps faster when you\'re close!',
      tip: 'Ask: Does it repeat? Does it stay in one spot in the sky? Could it be something made by people?',
      toddler: 'Drag the circle to find the beeping signals!',
    },
    quiz: [
      { q: 'Have scientists found proof of alien life?', a: ['Not yet, but they keep looking', 'Yes, aliens live on the Moon', 'Yes, they visit Earth every week', 'No, and nobody is looking anymore'], why: 'No strong evidence has been found yet, but the search is only just getting started.' },
      { q: 'About how many planets around other stars have we found?', a: ['More than 5,000', 'Just about 9', 'Exactly 100', 'None at all yet'], why: 'Since 1995, telescopes have found thousands of exoplanets, and more every year.' },
      { q: 'What is the Fermi paradox?', a: ['If aliens are likely, why haven\'t we heard from any?', 'Why the Moon looks bigger close to the horizon', 'Why some planes are able to fly upside down', 'Why rockets need stages to get all the way to orbit'], why: 'Enrico Fermi asked "Where is everybody?" Scientists have many possible answers.' },
      { q: 'Why is our galaxy so hard to search?', a: ['It\'s huge, and signals take ages to cross it', 'It\'s much too small to hold any planets', 'Aliens always hide behind the Sun\'s glare', 'Telescopes only work during the daytime'], why: 'The galaxy is about 100,000 light-years across. A message could take thousands of years to arrive!' },
      { q: 'A blurry UFO video is usually…', a: ['Something ordinary, like a balloon or a plane', 'Definitely an alien spaceship visiting us', 'A secret message sent from the future', 'A shooting star that fell out of the sky'], why: 'Investigators check simple explanations first, and they almost always turn out to be right.' },
      { q: '"Amazing claims need amazing evidence" means…', a: ['Big surprising ideas need really strong proof', 'Anything you see on the internet must be true', 'Only famous people are allowed to discover aliens', 'A good guess is just as good as checking'], why: 'Carl Sagan reminded us: the more surprising the idea, the stronger the proof has to be.' },
      { q: 'Where in our solar system might tiny life be hiding?', a: ['In the ocean under Europa\'s ice', 'On the blazing surface of the Sun', 'Inside the rings of Saturn', 'On the tip of a comet\'s tail'], why: 'Jupiter\'s moon Europa has a salty ocean under its ice. Saturn\'s moon Enceladus sprays water into space!' },
      { q: 'What was the first pulsar nicknamed when it was found in 1967?', h: true, a: ['LGM-1, for "Little Green Men"', 'E.T., for "Extra-Terrestrial"', 'Wow!, for a surprising signal', 'Fermi-1, for Enrico Fermi'], why: 'Jocelyn Bell Burnell found its super-regular beeps. It turned out to be a spinning dead star, not aliens!' },
      { q: '"We\'ve only searched a glass of water from the ocean" means…', h: true, a: ['We\'ve only searched a tiny part of space', 'Aliens must all live deep in the ocean', 'Space is full of salty ocean water', 'We should look for aliens in drinking cups'], why: 'Not finding something in a tiny search doesn\'t prove it isn\'t there.' },
    ],
    cards: [
      { e: '📡', n: 'Jocelyn Bell Burnell', y: '1967', f: 'Found the first pulsar. Its steady beeps were nicknamed "Little Green Men"!' },
      { e: '@aliens', n: 'Exoplanets', y: '1995', f: 'The first planet around a Sun-like star was found in 1995. Now we know of thousands!' },
    ],
    timeline: [{ y: 1995, s: 'The first planet around a Sun-like star is found' }],
  },
];
const QUIZ_LEN = 4, PER_RIGHT = 100, RETRY_PTS = 50;
